apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rmdworkloads.intel.com
spec:
  group: intel.com
  names:
    kind: RmdWorkload
    listKind: RmdWorkloadList
    plural: rmdworkloads
    singular: rmdworkload
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RmdWorkload is the Schema for the rmdworkloads API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RmdWorkloadSpec defines the desired state of RmdWorkload
          properties:
            cache:
              properties:
                max:
                  type: integer
                min:
                  type: integer
              required:
              - max
              - min
              type: object
            coreIds:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
            nodes:
              items:
                type: string
              type: array
            policy:
              type: string
            pstate:
              properties:
                monitoring:
                  type: string
                ratio:
                  type: string
              required:
              type: object
          required:
          - cache
          - coreIds
          - nodes
          type: object
        status:
          description: RmdWorkloadStatus defines the observed state of RmdWorkload
          properties:
            workloadStates:
              additionalProperties:
                properties:
                  cosName:
                    type: string
                  id:
                    type: string
                  response:
                    type: string
                  status:
                    type: string
                required:
                type: object
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: object
          required:
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
